#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Krampus.BinJson.SourceGenerators.Models;
using Krampus.BinJson.SourceGenerators.Utilities;

namespace Krampus.BinJson.SourceGenerators
{
    /// <summary>
    /// Emits C# code for BJson serializers
    /// </summary>
    internal static class CodeEmitter
    {
        public static string EmitSerializer(GeneratedTypeModel model)
        {
            var code = new CodeBuilder();

            // Header
            code.AppendLine("// <auto-generated />");
            code.AppendLine("#nullable enable");
            code.AppendLine();

            // Usings
            code.AddUsing("System");
            code.AddUsing("System.Collections.Generic");
            code.AddUsing("Krampus.BinJson");
            code.AddUsing("Krampus.BinJson.Serialization");
            code.WriteUsings();

            // Namespace (if not global)
            if (!string.IsNullOrEmpty(model.Namespace))
            {
                using (code.Namespace(model.Namespace))
                {
                    EmitSerializerClass(code, model);
                }
            }
            else
            {
                EmitSerializerClass(code, model);
            }

            return code.ToString();
        }

        private static void EmitSerializerClass(CodeBuilder code, GeneratedTypeModel model)
        {
            // Class XML documentation
            code.XmlComment("summary", $"Auto-generated BJson serializer for {model.FullTypeName}");
            code.XmlComment("remarks", "This class was generated by BJsonSourceGenerator and provides optimized serialization without reflection.");

            // Class declaration
            using (code.Class("internal sealed", $"{model.TypeName}_BJsonSerializer", $"BJsonConverter<{model.TypeName}>"))
            {
                // Cached custom member converters
                EmitCachedCustomConverterFields(code, model);

                // Cached version fields
                var versionFieldMap = EmitCachedVersionFields(code, model);

                // Cached extension-data keys
                EmitExtensionDataKnownPropertiesField(code, model);

                // Serialize method
                EmitSerializeMethod(code, model, versionFieldMap);
                code.AppendLine();

                // Deserialize method
                EmitDeserializeMethod(code, model, versionFieldMap);
            }
        }

        private static void EmitSerializeMethod(CodeBuilder code, GeneratedTypeModel model, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            code.XmlComment("summary", $"Serialize {model.TypeName} to BJsonValue");
            code.AppendLine($"public override BJsonValue Serialize({model.TypeName}? value, BJsonSerializationContext context)");

            using (code.Scope())
            {
                // Null check
                code.AppendLine("if (value == null)");
                using (code.Scope())
                {
                    code.AppendLine("return BJsonValue.Null;");
                }
                code.AppendLine();

                if (model.Configuration.IsPolymorphic)
                {
                    code.AppendLine($"if (value.GetType() != typeof({model.TypeName}))");
                    using (code.Scope())
                    {
                        code.AppendLine("return BJson.Serialize(value, value.GetType(), context.Options);");
                    }
                    code.AppendLine();
                }

                if (model.Configuration.HasOnSerializingHooks)
                {
                    code.AppendLine("Krampus.BinJson.Serialization.BJsonAttributeRuntimeSupport.InvokeOnSerializingHooks(value, context);");
                    code.AppendLine();
                }

                // Create BJsonObject
                code.AppendLine("var obj = new BJsonObject();");
                var discriminatorPropertyName = model.Configuration.IsPolymorphic
                    ? model.Configuration.TypeDiscriminatorPropertyName
                    : model.Configuration.InheritedPolymorphicDiscriminatorPropertyName;
                if (!string.IsNullOrWhiteSpace(discriminatorPropertyName))
                {
                    var discriminatorValueExpression = model.Configuration.IsPolymorphic
                        ? $"value.GetType().FullName ?? typeof({model.TypeName}).FullName!"
                        : $"\"{EscapeString(model.Configuration.InheritedPolymorphicDiscriminatorValue ?? model.FullTypeName)}\"";

                    code.AppendLine($"obj[\"{EscapeString(discriminatorPropertyName!)}\"] = BJsonValue.Create({discriminatorValueExpression});");
                }
                code.AppendLine();

                // Version local for predicates / mappers
                if (NeedsVersionLocal(model))
                    EmitVersionLocal(code, model);

                // Get serializable members sorted by Order
                var members = MemberOrdering.GetSerializableMembers(model.AllMembers);

                // Serialize each member
                foreach (var member in members)
                {
                    // Skip extension data member (handled separately)
                    if (member.IsExtensionData)
                        continue;

                    EmitMemberSerialization(code, member, model, versionFieldMap);
                }

                // Handle extension data
                if (model.ExtensionDataMember != null)
                {
                    code.AppendLine();
                    code.Comment("Extension data");
                    code.AppendLine($"if (value.{model.ExtensionDataMember.MemberName} != null)");
                    using (code.Scope())
                    {
                        code.AppendLine($"foreach (var kvp in value.{model.ExtensionDataMember.MemberName})");
                        using (code.Scope())
                        {
                            code.AppendLine("obj[kvp.Key] = kvp.Value;");
                        }
                    }
                }

                code.AppendLine();
                code.AppendLine("return BJsonValue.Create(obj);");
            }
        }

        private static void EmitMemberSerialization(CodeBuilder code, MemberModel member, GeneratedTypeModel model, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            var jsonName = member.JsonName ?? member.MemberName;
            var memberAccess = $"value.{member.MemberName}";

            var hasTypeVersionGuard = model.Configuration.TypeVersionRange != null;

            // Type-level version range guard
            if (hasTypeVersionGuard)
            {
                EmitVersionGuardOpen(code, model.Configuration.TypeVersionRange!, versionFieldMap);
            }

            // Version range guard
            if (member.Version != null)
            {
                EmitVersionGuardOpen(code, member, versionFieldMap);
            }

            // Handle ignore conditions
            if (member.IgnoreCondition == IgnoreCondition.WhenWritingNull)
            {
                code.AppendLine($"if ({memberAccess} != null)");
                using (code.Scope())
                {
                    EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
                }
            }
            else if (member.IgnoreCondition == IgnoreCondition.WhenWritingDefault
                     || (member.IgnoreCondition == IgnoreCondition.WhenWritingCustomDefault && member.DefaultValue?.HasProviderMethod != true))
            {
                var typeString = code.FormatTypeName(member.MemberType);
                code.AppendLine($"if (!EqualityComparer<{typeString}>.Default.Equals({memberAccess}, default({typeString})))");
                using (code.Scope())
                {
                    EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
                }
            }
            else if (member.IgnoreCondition == IgnoreCondition.WhenWritingCustomDefault)
            {
                var typeString = code.FormatTypeName(member.MemberType);
                code.AppendLine($"if (!EqualityComparer<{typeString}>.Default.Equals({memberAccess}, ({typeString})(object){GetDefaultProviderInvocationExpression(member, model)}!))");
                using (code.Scope())
                {
                    EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
                }
            }
            else if (member.IgnoreCondition == IgnoreCondition.WhenWriting)
            {
                // WhenWriting: skip serialization entirely
            }
            else
            {
                // Never, Always (filtered upstream), WhenReading — always serialize
                EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
            }

            if (member.Version != null)
            {
                EmitVersionGuardClose(code);
            }

            if (hasTypeVersionGuard)
            {
                EmitVersionGuardClose(code);
            }
        }

        private static void EmitSerializeWithPredicate(CodeBuilder code, string jsonName, string memberAccess, MemberModel member, GeneratedTypeModel model)
        {
            // Static predicate check
            if (member.IgnoreWhenMethod != null)
            {
                code.AppendLine($"if (!{model.TypeName}.{member.IgnoreWhenMethod}({memberAccess}, \"{jsonName}\", _version))");
                using (code.Scope())
                {
                    EmitPropertyAssignmentWithMapper(code, jsonName, memberAccess, member, model);
                }
            }
            else
            {
                EmitPropertyAssignmentWithMapper(code, jsonName, memberAccess, member, model);
            }
        }

        private static void EmitPropertyAssignmentWithMapper(CodeBuilder code, string jsonName, string memberAccess, MemberModel member, GeneratedTypeModel model)
        {
            string valueExpr;

            if (member.CustomConverterType != null)
            {
                valueExpr = $"{GetCustomConverterFieldName(member)}.Serialize({memberAccess}, context)";
            }
            else if (member.CustomConverterFactoryType != null)
            {
                valueExpr = $"{GetCustomConverterFieldName(member)}.Serialize({memberAccess}, context)";
            }
            else
            {
                valueExpr = GetSerializationExpression(member.MemberType, memberAccess, "context");
            }

            // Value mapper (write direction)
            if (member.ValueMapperMethod != null)
                valueExpr = $"{model.TypeName}.{member.ValueMapperMethod}({valueExpr}, \"{jsonName}\", _version, false)";

            if (member.NumberHandling != 0)
                valueExpr = $"Krampus.BinJson.Serialization.BJsonAttributeRuntimeSupport.ApplyNumberHandlingOnWrite({valueExpr}, {memberAccess}, {member.NumberHandling})";

            code.AppendLine($"obj[\"{jsonName}\"] = {valueExpr};");
        }

        /// <summary>
        /// Generate optimized serialization expression based on source type
        /// </summary>
        private static string GetSerializationExpression(string typeName, string valueExpression, string contextName)
        {
            // Strip nullable suffix for analysis
            var baseType = typeName.TrimEnd('?');

            // Primitives and simple types - use BJsonValue.Create directly
            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                case "byte":
                case "Byte":
                case "System.Byte":
                case "sbyte":
                case "SByte":
                case "System.SByte":
                case "short":
                case "Int16":
                case "System.Int16":
                case "ushort":
                case "UInt16":
                case "System.UInt16":
                case "int":
                case "Int32":
                case "System.Int32":
                case "uint":
                case "UInt32":
                case "System.UInt32":
                case "long":
                case "Int64":
                case "System.Int64":
                case "ulong":
                case "UInt64":
                case "System.UInt64":
                case "float":
                case "Single":
                case "System.Single":
                case "double":
                case "Double":
                case "System.Double":
                case "string":
                case "String":
                case "System.String":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonValue itself
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                    return valueExpression;

                // BJsonObject
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonArray
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonBinary
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return $"BJsonValue.Create({valueExpression})";

                // For all other types (complex objects, collections, enums, etc.)
                // use context.Serialize
                default:
                    return $"{contextName}.Serialize({valueExpression})";
            }
        }

        private static void EmitDeserializeMethod(CodeBuilder code, GeneratedTypeModel model, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            code.XmlComment("summary", $"Deserialize BJsonValue to {model.TypeName}");
            code.AppendLine($"public override {model.TypeName}? Deserialize(BJsonValue value, BJsonSerializationContext context)");

            using (code.Scope())
            {
                // Null check
                code.AppendLine("if (value.IsNull)");
                using (code.Scope())
                {
                    code.AppendLine("return null;");
                }
                code.AppendLine();

                // Extract object
                code.AppendLine("var obj = value.ObjectValue;");
                code.AppendLine();

                if (model.Configuration.IsPolymorphic && model.Configuration.DerivedTypes.Count > 0)
                {
                    code.AppendLine($"if (obj.TryGetValue(\"{model.Configuration.TypeDiscriminatorPropertyName}\", out var _typeDiscriminatorToken) && _typeDiscriminatorToken.TryGetString(out var _typeDiscriminator))");
                    using (code.Scope())
                    {
                        foreach (var derived in model.Configuration.DerivedTypes)
                        {
                            var derivedTypeName = derived.DerivedType;
                            var discriminator = derived.TypeDiscriminator ?? derived.DerivedType;
                            code.AppendLine($"if (string.Equals(_typeDiscriminator, \"{EscapeString(discriminator)}\", StringComparison.Ordinal) || string.Equals(_typeDiscriminator, \"{EscapeString(derivedTypeName)}\", StringComparison.Ordinal))");
                            using (code.Scope())
                            {
                                code.AppendLine($"return ({model.TypeName}?)BJson.Deserialize(value, typeof({derivedTypeName}), context.Options);");
                            }
                        }

                        code.AppendLine($"if (!string.Equals(_typeDiscriminator, typeof({model.TypeName}).FullName, StringComparison.Ordinal))");
                        using (code.Scope())
                        {
                            code.AppendLine("var _resolvedDiscriminatorType = Type.GetType(_typeDiscriminator, throwOnError: false); ");
                            code.AppendLine($"if (_resolvedDiscriminatorType != null && typeof({model.TypeName}).IsAssignableFrom(_resolvedDiscriminatorType) && _resolvedDiscriminatorType != typeof({model.TypeName}))");
                            using (code.Scope())
                            {
                                code.AppendLine($"return ({model.TypeName}?)BJson.Deserialize(value, _resolvedDiscriminatorType, context.Options);");
                            }
                        }
                    }
                    code.AppendLine();
                }

                if (model.Configuration.IsPolymorphic && model.IsAbstract)
                {
                    code.AppendLine("return null;");
                    code.AppendLine();
                }

                // Version local for predicates / mappers
                if (NeedsVersionLocal(model))
                    EmitVersionLocal(code, model);
                code.AppendLine();

                // Get deserializable members
                var members = MemberOrdering.GetDeserializableMembers(model.AllMembers)
                    .Where(m => !m.IsExtensionData)
                    .ToList();

                // Track which properties were actually present in JSON (for required validation)
                var requiredMembers = members.Where(m => m.IsRequired || m.RequiredWhenMethod != null).ToList();
                if (requiredMembers.Any())
                {
                    code.Comment("Track presence of required members");
                    foreach (var reqMember in requiredMembers)
                    {
                        code.AppendLine($"var _has_{reqMember.MemberName} = false;");
                    }
                    code.AppendLine();
                }

                // Handle constructor-based or factory-method-based deserialization
                var hasParameterizedFactory = !string.IsNullOrEmpty(model.Configuration.FactoryMethodName)
                    && model.Configuration.FactoryMethodParameters != null
                    && model.Configuration.FactoryMethodParameters.Count > 0;

                if ((model.Constructor != null && !model.Constructor.IsParameterless) || hasParameterizedFactory)
                {
                    EmitConstructorOrFactoryDeserialization(code, model, members, requiredMembers, versionFieldMap);
                }
                else
                {
                    // Parameterless constructor, parameterless factory, or value type
                    EmitParameterlessDeserialization(code, model, members, requiredMembers, versionFieldMap);
                }

                // Handle extension data
                if (model.ExtensionDataMember != null)
                {
                    code.AppendLine();
                    EmitExtensionDataDeserialization(code, model, members);
                }

                // Validate required members
                if (requiredMembers.Any())
                {
                    code.AppendLine();
                    EmitRequiredMemberValidation(code, requiredMembers, model);
                }

                if (model.Configuration.HasOnDeserializedHooks)
                {
                    code.AppendLine();
                    code.AppendLine("Krampus.BinJson.Serialization.BJsonAttributeRuntimeSupport.InvokeOnDeserializedHooks(instance!, context);");
                }

                code.AppendLine();
                code.AppendLine("return instance;");
            }
        }

        private static void EmitConstructorOrFactoryDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members, List<MemberModel> requiredMembers, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            // Prefer factory method parameters over constructor if both exist
            var parameters = model.Configuration.FactoryMethodParameters ?? model.Constructor?.Parameters;
            var isUsingFactory = !string.IsNullOrEmpty(model.Configuration.FactoryMethodName) 
                && model.Configuration.FactoryMethodParameters != null;

            if (parameters == null || parameters.Count == 0)
            {
                // Fallback to parameterless if something went wrong
                EmitParameterlessDeserialization(code, model, members, requiredMembers, versionFieldMap);
                return;
            }

            code.Comment(isUsingFactory ? "Extract factory method parameters" : "Extract constructor parameters");

            // Extract each parameter from JSON
            foreach (var param in parameters)
            {
                // Use the pre-matched JsonName from parameter matching
                var jsonName = param.JsonName ?? param.ParameterName;

                // Check if this parameter corresponds to a required member
                var isRequired = param.MatchingMember?.IsRequired ?? false;

                EmitParameterExtraction(code, param, jsonName, isRequired);
            }

            code.AppendLine();
            code.Comment(isUsingFactory ? "Create instance via factory method" : "Create instance via constructor");

            var paramList = string.Join(", ", parameters.Select(p => p.IsNullable || p.IsValueType ? p.ParameterName : $"{p.ParameterName}!"));
            if (!string.IsNullOrEmpty(model.Configuration.FactoryMethodName))
                code.AppendLine($"var instance = {model.TypeName}.{model.Configuration.FactoryMethodName}({paramList});");
            else if (model.IsAbstract)
                code.AppendLine($"var instance = default({model.TypeName});");
            else
                code.AppendLine($"var instance = new {model.TypeName}({paramList});");
            code.AppendLine();

            // Set remaining properties not in constructor/factory parameters
            var paramNames = new HashSet<string>(
                parameters.Select(p => p.ParameterName),
                StringComparer.OrdinalIgnoreCase);

            var remainingMembers = members
                .Where(m => !paramNames.Contains(m.MemberName))
                .ToList();

            if (remainingMembers.Any())
            {
                code.Comment("Set remaining properties");
                foreach (var member in remainingMembers)
                {
                    EmitPropertyDeserialization(code, member, requiredMembers.Contains(member), model, versionFieldMap);
                }
            }
        }

        private static void EmitParameterlessDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members, List<MemberModel> requiredMembers, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            code.Comment("Create instance");
            if (!string.IsNullOrEmpty(model.Configuration.FactoryMethodName))
                code.AppendLine($"var instance = {model.TypeName}.{model.Configuration.FactoryMethodName}();");
            else if (model.IsAbstract)
                code.AppendLine($"var instance = default({model.TypeName});");
            else
                code.AppendLine($"var instance = new {model.TypeName}();");
            code.AppendLine();

            if (members.Any())
            {
                code.Comment("Deserialize properties");
                foreach (var member in members)
                {
                    EmitPropertyDeserialization(code, member, requiredMembers.Contains(member), model, versionFieldMap);
                }
            }
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static void EmitParameterExtraction(CodeBuilder code, ConstructorParameterModel param, string jsonName, bool isRequired)
        {
            code.AppendLine($"var _has_{param.ParameterName}Param = obj.TryGetValue(\"{jsonName}\", out var {param.ParameterName}Value);");
            code.AppendLine($"var {param.ParameterName} = _has_{param.ParameterName}Param");

            var deserializationCode = GetDeserializationExpression(param.ParameterType, $"{param.ParameterName}Value", "context");
            code.AppendLine($"    ? {deserializationCode}");
            code.AppendLine($"    : {(param.IsNullable || param.IsValueType ? $"default({param.ParameterType})" : "default!")};");

            // Track required member presence
            if (isRequired)
            {
                code.AppendLine($"if (_has_{param.ParameterName}Param) _has_{param.ParameterName} = true;");
            }
        }

        private static void EmitPropertyDeserialization(CodeBuilder code, MemberModel member, bool isRequired, GeneratedTypeModel model, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            var jsonName = member.JsonName ?? member.MemberName;
            var legacyName = member.Version?.RenamedFrom;
            var varName = $"{member.MemberName}Value";
            var typeName = member.MemberType;
            var requiredCondition = BuildRequiredConditionExpression(member, model);

            var hasTypeVersionGuard = model.Configuration.TypeVersionRange != null;

            // Type-level version range guard
            if (hasTypeVersionGuard)
                EmitVersionGuardOpen(code, model.Configuration.TypeVersionRange!, versionFieldMap);

            // Version range guard
            if (member.Version != null)
                EmitVersionGuardOpen(code, member, versionFieldMap);

            // Build TryGetValue condition (with optional legacy name fallback)
            string tryGetCondition;
            var tryGetParts = new List<string> { $"obj.TryGetValue(\"{jsonName}\", out var {varName})" };
            if (legacyName != null)
                tryGetParts.Add($"obj.TryGetValue(\"{legacyName}\", out {varName})");
            foreach (var alias in member.Aliases)
                tryGetParts.Add($"obj.TryGetValue(\"{EscapeString(alias)}\", out {varName})");
            tryGetCondition = string.Join(" || ", tryGetParts);

            code.AppendLine($"if ({tryGetCondition})");
            using (code.Scope())
            {
                if (member.DefaultValue != null && member.IsValueType && !member.IsNullable)
                {
                    code.AppendLine($"if ({varName}.IsNull)");
                    using (code.Scope())
                    {
                        EmitDefaultAssignment(code, member, model, typeName);
                        EmitRequiredPresenceMark(code, member, isRequired, requiredCondition);
                    }
                    code.AppendLine("else");
                    using (code.Scope())
                    {
                        EmitDeserializationBody(code, member, isRequired, requiredCondition, model, varName, jsonName);
                    }
                }
                else
                {
                    EmitDeserializationBody(code, member, isRequired, requiredCondition, model, varName, jsonName);
                }
            }

            // else: key absent — inject default value
            if (member.DefaultValue != null)
            {
                code.AppendLine("else");
                using (code.Scope())
                {
                    EmitDefaultAssignment(code, member, model, typeName);
                    EmitRequiredPresenceMark(code, member, isRequired, requiredCondition);
                }
            }
            else if (isRequired)
            {
                code.AppendLine("else");
                using (code.Scope())
                {
                    if (requiredCondition == "true")
                    {
                        code.AppendLine($"throw new Krampus.BinJson.Error.BJsonValidationException($\"Required member '{jsonName}' was not present in the JSON.\");");
                    }
                    else
                    {
                        code.AppendLine($"if (context.Options.StrictMode && ({requiredCondition}))");
                        using (code.Scope())
                        {
                            code.AppendLine($"throw new Krampus.BinJson.Error.BJsonValidationException($\"Required member '{jsonName}' was not present in the JSON.\");");
                        }
                    }
                }
            }

            if (member.Version != null)
                EmitVersionGuardClose(code);

            if (hasTypeVersionGuard)
                EmitVersionGuardClose(code);
        }

        private static void EmitDeserializationBody(CodeBuilder code, MemberModel member, bool isRequired, string? requiredCondition, GeneratedTypeModel model, string varName, string jsonName)
        {
                // Predicate check
                if (member.IgnoreWhenMethod != null)
                {
                    code.AppendLine($"if (!{model.TypeName}.{member.IgnoreWhenMethod}({varName}, \"{jsonName}\", _version))");
                    using (code.Scope())
                    {
                        EmitDeserializeAssignment(code, member, varName, isRequired, requiredCondition, model);
                    }
                }
                else
                {
                    EmitDeserializeAssignment(code, member, varName, isRequired, requiredCondition, model);
                }
        }

        private static void EmitDefaultAssignment(CodeBuilder code, MemberModel member, GeneratedTypeModel model, string typeName)
        {
            if (member.DefaultValue == null)
                return;

            if (member.DefaultValue.HasProviderMethod)
            {
                code.AppendLine($"instance.{member.MemberName} = ({typeName})(object){GetDefaultProviderInvocationExpression(member, model)}!;");
            }
            else if (member.DefaultValue.HasConstant)
            {
                var constVal = FormatConstantLiteral(member.DefaultValue.ConstantValue);
                code.AppendLine($"instance.{member.MemberName} = ({typeName})(object){constVal}!;");
            }
        }

        private static void EmitDeserializeAssignment(CodeBuilder code, MemberModel member, string varName, bool isRequired, string? requiredCondition, GeneratedTypeModel model)
        {
            // Value mapper (read direction) before deserialization
            string inputVar = varName;
            if (member.ValueMapperMethod != null)
            {
                code.AppendLine($"var {varName}_mapped = {model.TypeName}.{member.ValueMapperMethod}({varName}, \"{member.JsonName ?? member.MemberName}\", _version, true);");
                inputVar = $"{varName}_mapped";
            }

            if (member.CustomConverterType != null)
            {
                code.AppendLine($"instance.{member.MemberName} = {GetCustomConverterFieldName(member)}.Deserialize({inputVar}, context);");
            }
            else if (member.CustomConverterFactoryType != null)
            {
                code.AppendLine($"instance.{member.MemberName} = {GetCustomConverterFieldName(member)}.Deserialize({inputVar}, context);");
            }
            else
            {
                var deserializationCode = GetDeserializationExpression(member.MemberType, inputVar, "context");
                var requiresNullGuard = !member.IsNullable && !member.IsValueType && UsesContextDeserialize(member.MemberType);

                if (member.NumberHandling != 0)
                {
                    var numericTypeName = code.FormatTypeName(member.MemberType);
                    if (!member.IsValueType && numericTypeName.EndsWith("?", StringComparison.Ordinal))
                        numericTypeName = numericTypeName.Substring(0, numericTypeName.Length - 1);

                    code.AppendLine($"if (Krampus.BinJson.Serialization.BJsonAttributeRuntimeSupport.TryDeserializeNumericMember({inputVar}, typeof({numericTypeName}), {member.NumberHandling}, out var parsed{member.MemberName}))");
                    using (code.Scope())
                    {
                        code.AppendLine($"instance.{member.MemberName} = ({code.FormatTypeName(member.MemberType)})parsed{member.MemberName}!;");
                    }
                    code.AppendLine("else");
                    using (code.Scope())
                    {
                        if (requiresNullGuard)
                        {
                            code.AppendLine($"var deserialized{member.MemberName} = {deserializationCode};");
                            code.AppendLine($"if (deserialized{member.MemberName} != null)");
                            using (code.Scope())
                            {
                                code.AppendLine($"instance.{member.MemberName} = deserialized{member.MemberName};");
                            }
                        }
                        else
                        {
                            code.AppendLine($"instance.{member.MemberName} = {deserializationCode};");
                        }
                    }

                    EmitRequiredPresenceMark(code, member, isRequired, requiredCondition);
                    return;
                }

                if (requiresNullGuard)
                {
                    code.AppendLine($"var deserialized{member.MemberName} = {deserializationCode};");
                    code.AppendLine($"if (deserialized{member.MemberName} != null)");
                    using (code.Scope())
                    {
                        code.AppendLine($"instance.{member.MemberName} = deserialized{member.MemberName};");
                    }
                }
                else
                {
                    code.AppendLine($"instance.{member.MemberName} = {deserializationCode};");
                }
            }

            EmitRequiredPresenceMark(code, member, isRequired, requiredCondition);
        }

        /// <summary>
        /// Generate optimized deserialization expression based on target type
        /// </summary>
        private static string GetDeserializationExpression(string typeName, string valueName, string contextName)
        {
            // Strip nullable suffix for analysis
            var baseType = typeName.TrimEnd('?');

            // Primitives - use direct BJsonValue properties
            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                    return $"{valueName}.BoolValue";

                case "byte":
                case "Byte":
                case "System.Byte":
                    return $"{valueName}.ByteValue";

                case "sbyte":
                case "SByte":
                case "System.SByte":
                    return $"{valueName}.SByteValue";

                case "short":
                case "Int16":
                case "System.Int16":
                    return $"{valueName}.ShortValue";

                case "ushort":
                case "UInt16":
                case "System.UInt16":
                    return $"{valueName}.UShortValue";

                case "int":
                case "Int32":
                case "System.Int32":
                    return $"{valueName}.IntValue";

                case "uint":
                case "UInt32":
                case "System.UInt32":
                    return $"{valueName}.UIntValue";

                case "long":
                case "Int64":
                case "System.Int64":
                    return $"{valueName}.LongValue";

                case "ulong":
                case "UInt64":
                case "System.UInt64":
                    return $"{valueName}.ULongValue";

                case "float":
                case "Single":
                case "System.Single":
                    return $"{valueName}.FloatValue";

                case "double":
                case "Double":
                case "System.Double":
                    return $"{valueName}.DoubleValue";

                case "string":
                case "String":
                case "System.String":
                    return $"{valueName}.StringValue";

                // BJsonValue itself
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                    return valueName;

                // BJsonObject
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                    return $"{valueName}.ObjectValue";

                // BJsonArray
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                    return $"{valueName}.ArrayValue";

                // BJsonBinary
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return $"{valueName}.BinaryValue";

                // For all other types (complex objects, collections, enums, etc.)
                // use context.Deserialize<T>
                default:
                    return $"{contextName}.Deserialize<{typeName}>({valueName})";
            }
        }

        private static bool UsesContextDeserialize(string typeName)
        {
            var baseType = typeName.TrimEnd('?');

            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                case "byte":
                case "Byte":
                case "System.Byte":
                case "sbyte":
                case "SByte":
                case "System.SByte":
                case "short":
                case "Int16":
                case "System.Int16":
                case "ushort":
                case "UInt16":
                case "System.UInt16":
                case "int":
                case "Int32":
                case "System.Int32":
                case "uint":
                case "UInt32":
                case "System.UInt32":
                case "long":
                case "Int64":
                case "System.Int64":
                case "ulong":
                case "UInt64":
                case "System.UInt64":
                case "float":
                case "Single":
                case "System.Single":
                case "double":
                case "Double":
                case "System.Double":
                case "string":
                case "String":
                case "System.String":
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return false;

                default:
                    return true;
            }
        }

        private static void EmitExtensionDataDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members)
        {
            var extensionMember = model.ExtensionDataMember!;

            code.Comment("Collect extension data (unknown properties)");
            code.AppendLine($"instance.{extensionMember.MemberName} = new Dictionary<string, BJsonValue>();");
            code.AppendLine("foreach (var kvp in obj)");
            using (code.Scope())
            {
                code.AppendLine("if (!_knownProperties.Contains(kvp.Key))");
                using (code.Scope())
                {
                    code.AppendLine($"instance.{extensionMember.MemberName}[kvp.Key] = kvp.Value;");
                }
            }
        }

        /// <summary>
        /// Emit validation checks for required members
        /// </summary>
        private static void EmitRequiredMemberValidation(CodeBuilder code, List<MemberModel> requiredMembers, GeneratedTypeModel model)
        {
            code.Comment("Validate required members");

            foreach (var member in requiredMembers)
            {
                var jsonName = member.JsonName ?? member.MemberName;
                var requiredCondition = BuildRequiredConditionExpression(member, model) ?? "false";
                code.AppendLine($"if (({requiredCondition}) && !_has_{member.MemberName})");
                using (code.Scope())
                {
                    code.AppendLine($"throw new Krampus.BinJson.Error.BJsonValidationException($\"Required member '{jsonName}' was not present in the JSON.\");");
                }
            }
        }

        private static bool NeedsVersionLocal(GeneratedTypeModel model)
        {
            if (model.Configuration.VersionContext != null)
                return true;

            if (model.Configuration.TypeVersionRange != null)
                return true;

            foreach (var member in model.AllMembers)
            {
                if (member.Version != null
                    || member.IgnoreWhenMethod != null
                    || member.ValueMapperMethod != null
                    || member.RequiredWhenMethod != null
                    || member.DefaultValue?.ProviderAcceptsVersion == true)
                    return true;
            }

            return false;
        }

        private static void EmitVersionLocal(CodeBuilder code, GeneratedTypeModel model)
        {
            var vc = model.Configuration.VersionContext;
            if (vc == null)
            {
                code.AppendLine("System.IComparable? _version = context.Options?.Version;");
            }
            else
            {
                code.AppendLine($"System.IComparable? _version = context.Options?.Version ?? _cachedContextVersion;");
            }
        }

        /// <summary>
        /// Emit cached static readonly fields for all versions used in the type
        /// </summary>
        private static IReadOnlyDictionary<string, string>? EmitCachedVersionFields(CodeBuilder code, GeneratedTypeModel model)
        {
            var vc = model.Configuration.VersionContext;
            var typeRange = model.Configuration.TypeVersionRange;

            // Collect all unique versions mentioned in the type
            var versions = new HashSet<string>(StringComparer.Ordinal);

            string? versionTypeName = vc?.VersionTypeName;

            if (versionTypeName == null)
            {
                versionTypeName = typeRange?.VersionTypeName
                    ?? model.AllMembers.FirstOrDefault(m => m.Version != null)?.Version?.VersionTypeName;
            }

            if (versionTypeName == null)
                return null;

            // Add the context version
            if (vc != null && !string.IsNullOrEmpty(vc.IntroducedIn))
                versions.Add(vc.IntroducedIn!);

            // Add type-level version boundaries
            if (typeRange != null)
            {
                if (!string.IsNullOrEmpty(typeRange.IntroducedIn))
                    versions.Add(typeRange.IntroducedIn!);
                if (!string.IsNullOrEmpty(typeRange.RemovedIn))
                    versions.Add(typeRange.RemovedIn!);
            }

            // Add all member version boundaries
            foreach (var member in model.AllMembers)
            {
                if (member.Version != null)
                {
                    if (!string.IsNullOrEmpty(member.Version.IntroducedIn))
                        versions.Add(member.Version.IntroducedIn!);
                    if (!string.IsNullOrEmpty(member.Version.RemovedIn))
                        versions.Add(member.Version.RemovedIn!);
                }
            }

            if (versions.Count == 0)
                return null;

            code.Comment("Cached parsed versions for performance");

            var versionFieldMap = new Dictionary<string, string>(StringComparer.Ordinal);

            // Emit the main context version (always present if we have a version context)
            if (vc != null && !string.IsNullOrEmpty(vc.IntroducedIn))
            {
                code.AppendLine($"private static readonly System.IComparable _cachedContextVersion = {vc.VersionTypeName}.Parse(\"{vc.IntroducedIn}\");");
                versionFieldMap[vc.IntroducedIn!] = "_cachedContextVersion";
            }

            // Emit individual version fields for member boundaries
            var versionIndex = 0;

            foreach (var versionString in versions.OrderBy(v => v))
            {
                if (versionFieldMap.ContainsKey(versionString))
                {
                    // Already emitted
                    continue;
                }

                var fieldName = $"_cachedVersion{versionIndex++}";
                versionFieldMap[versionString] = fieldName;
                code.AppendLine($"private static readonly System.IComparable {fieldName} = {versionTypeName}.Parse(\"{versionString}\");");
            }

            code.AppendLine();
            return versionFieldMap;
        }

        private static void EmitExtensionDataKnownPropertiesField(CodeBuilder code, GeneratedTypeModel model)
        {
            if (model.ExtensionDataMember == null)
                return;

            var knownProperties = model.AllMembers
                .Where(m => !m.IsExtensionData)
                .SelectMany(m =>
                {
                    if (m.Version?.RenamedFrom is string renamedFrom)
                    {
                        var names = new List<string> { m.JsonName ?? m.MemberName, renamedFrom };
                        names.AddRange(m.Aliases);
                        return names;
                    }

                    var defaultNames = new List<string> { m.JsonName ?? m.MemberName };
                    defaultNames.AddRange(m.Aliases);
                    return defaultNames;
                })
                .Distinct(StringComparer.Ordinal)
                .ToList();

            code.Comment("Cached known property names for extension data filtering");
            var knownPropsInitializer = string.Join(", ", knownProperties.Select(p => $"\"{EscapeStringLiteral(p)}\""));
            code.AppendLine($"private static readonly HashSet<string> _knownProperties = new HashSet<string>(StringComparer.Ordinal) {{ {knownPropsInitializer} }};");
            code.AppendLine();
        }

        private static void EmitVersionGuardOpen(CodeBuilder code, MemberModel member, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            var v = member.Version!;

            string GetVersionReference(string versionString)
            {
                // If we have a cached field, use it; otherwise, parse inline (fallback)
                if (versionFieldMap != null && versionFieldMap.TryGetValue(versionString, out var fieldName))
                {
                    return fieldName;
                }
                return $"{v.VersionTypeName}.Parse(\"{versionString}\")";
            }

            if (v.IntroducedIn != null && v.RemovedIn != null)
            {
                var introRef = GetVersionReference(v.IntroducedIn);
                var removedRef = GetVersionReference(v.RemovedIn);
                code.AppendLine($"if (_version == null || (_version.CompareTo({introRef}) >= 0 && _version.CompareTo({removedRef}) < 0))");
            }
            else if (v.IntroducedIn != null)
            {
                var introRef = GetVersionReference(v.IntroducedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({introRef}) >= 0)");
            }
            else if (v.RemovedIn != null)
            {
                var removedRef = GetVersionReference(v.RemovedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({removedRef}) < 0)");
            }
            code.OpenBrace();
        }

        private static void EmitVersionGuardOpen(CodeBuilder code, VersionInfo versionInfo, IReadOnlyDictionary<string, string>? versionFieldMap)
        {
            string GetVersionReference(string versionString)
            {
                if (versionFieldMap != null && versionFieldMap.TryGetValue(versionString, out var fieldName))
                {
                    return fieldName;
                }

                return $"{versionInfo.VersionTypeName}.Parse(\"{versionString}\")";
            }

            if (versionInfo.IntroducedIn != null && versionInfo.RemovedIn != null)
            {
                var introRef = GetVersionReference(versionInfo.IntroducedIn);
                var removedRef = GetVersionReference(versionInfo.RemovedIn);
                code.AppendLine($"if (_version == null || (_version.CompareTo({introRef}) >= 0 && _version.CompareTo({removedRef}) < 0))");
            }
            else if (versionInfo.IntroducedIn != null)
            {
                var introRef = GetVersionReference(versionInfo.IntroducedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({introRef}) >= 0)");
            }
            else if (versionInfo.RemovedIn != null)
            {
                var removedRef = GetVersionReference(versionInfo.RemovedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({removedRef}) < 0)");
            }

            code.OpenBrace();
        }

        private static void EmitVersionGuardClose(CodeBuilder code)
        {
            code.CloseBrace();
        }

        private static void EmitCachedCustomConverterFields(CodeBuilder code, GeneratedTypeModel model)
        {
            var customMembers = model.AllMembers
                .Where(HasCustomMemberConverter)
                .ToList();

            if (customMembers.Count == 0)
                return;

            code.Comment("Cached custom converters for member-level attributes");
            foreach (var member in customMembers)
            {
                string fieldName = GetCustomConverterFieldName(member);
                string factoryMethodName = GetCustomConverterFactoryMethodName(member);
                code.AppendLine($"private static readonly IBJsonConverter {fieldName} = {factoryMethodName}();");
                code.AppendLine($"private static IBJsonConverter {factoryMethodName}()");
                code.OpenBrace();
                if (!string.IsNullOrWhiteSpace(member.CustomConverterType))
                {
                    code.AppendLine($"if (Activator.CreateInstance(typeof({member.CustomConverterType})) is not IBJsonConverter converter)");
                    code.OpenBrace();
                    code.AppendLine($"throw new BJsonConverterException(\"Converter '{member.CustomConverterType}' could not be instantiated.\");");
                    code.CloseBrace();
                    code.AppendLine("return converter;");
                }
                else
                {
                    var memberTypeName = code.FormatTypeName(member.MemberType);
                    code.AppendLine($"if (Activator.CreateInstance(typeof({member.CustomConverterFactoryType})) is not IBJsonConverterFactory factory)");
                    code.OpenBrace();
                    code.AppendLine($"throw new BJsonConverterException(\"Converter factory '{member.CustomConverterFactoryType}' could not be instantiated.\");");
                    code.CloseBrace();
                    code.AppendLine($"if (!factory.CanConvert(typeof({memberTypeName})))");
                    code.OpenBrace();
                    code.AppendLine($"throw new BJsonConverterException(\"Converter factory '{member.CustomConverterFactoryType}' cannot convert member '{member.MemberName}'.\");");
                    code.CloseBrace();
                    code.AppendLine($"return factory.CreateConverter(typeof({memberTypeName}));");
                }
                code.CloseBrace();
            }

            code.AppendLine();
        }

        private static string GetCustomConverterFieldName(MemberModel member)
        {
            var sb = new StringBuilder("_memberConverter_");
            AppendIdentifierPart(sb, member.MemberName);
            return sb.ToString();
        }

        private static string GetCustomConverterFactoryMethodName(MemberModel member)
        {
            var sb = new StringBuilder("CreateMemberConverter_");
            AppendIdentifierPart(sb, member.MemberName);
            return sb.ToString();
        }

        private static bool HasCustomMemberConverter(MemberModel member)
        {
            return !string.IsNullOrWhiteSpace(member.CustomConverterType)
                || !string.IsNullOrWhiteSpace(member.CustomConverterFactoryType);
        }

        private static void EmitRequiredPresenceMark(CodeBuilder code, MemberModel member, bool isRequired, string? requiredCondition)
        {
            if (!isRequired)
                return;

            if (requiredCondition == "true")
                code.AppendLine($"_has_{member.MemberName} = true;");
            else
                code.AppendLine($"if ({requiredCondition}) _has_{member.MemberName} = true;");
        }

        private static string? BuildRequiredConditionExpression(MemberModel member, GeneratedTypeModel model)
        {
            if (member.IsRequired)
                return "true";

            if (member.RequiredWhenMethod == null)
                return null;

            var jsonName = EscapeString(member.JsonName ?? member.MemberName);
            return member.RequiredWhenParameterCount switch
            {
                0 => $"{model.TypeName}.{member.RequiredWhenMethod}()",
                1 => $"{model.TypeName}.{member.RequiredWhenMethod}(_version)",
                _ => $"{model.TypeName}.{member.RequiredWhenMethod}(\"{jsonName}\", _version)"
            };
        }

        private static string GetDefaultProviderInvocationExpression(MemberModel member, GeneratedTypeModel model)
        {
            var provider = member.DefaultValue?.ProviderMethod;
            if (provider == null)
                return "default";

            if (member.DefaultValue?.ProviderAcceptsVersion == true)
                return $"{model.TypeName}.{provider}(_version)";

            return $"{model.TypeName}.{provider}()";
        }

        private static void AppendIdentifierPart(StringBuilder sb, string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                sb.Append("member");
                return;
            }

            if (!IsIdentifierStart(text[0]))
                sb.Append('_');

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                sb.Append(IsIdentifierPart(c) ? c : '_');
            }
        }

        private static bool IsIdentifierStart(char c)
        {
            return char.IsLetter(c) || c == '_';
        }

        private static bool IsIdentifierPart(char c)
        {
            return char.IsLetterOrDigit(c) || c == '_';
        }

        private static string FormatConstantLiteral(object? value)
        {
            if (value == null) return "null";
            if (value is string s) return $"\"{ EscapeStringLiteral(s) }\"";
            if (value is bool b) return b ? "true" : "false";
            if (value is char c) return $"'{c}'";
            if (value is float f) return $"{f}f";
            if (value is double d) return $"{d}";
            return value.ToString() ?? "default";
        }

        private static string EscapeStringLiteral(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t")
                .Replace("\0", "\\0");
        }
    }
}
