#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Krampus.BinJson.SourceGenerators.Models;
using Krampus.BinJson.SourceGenerators.Utilities;

namespace Krampus.BinJson.SourceGenerators
{
    /// <summary>
    /// Emits C# code for BJson serializers
    /// </summary>
    internal static class CodeEmitter
    {
        // Thread-local cache map for version strings -> field names during generation
        [ThreadStatic]
        private static Dictionary<string, string>? _versionFieldMap;

        public static string EmitSerializer(GeneratedTypeModel model)
        {
            var code = new CodeBuilder();

            // Initialize version field map
            _versionFieldMap = null;

            // Header
            code.AppendLine("// <auto-generated />");
            code.AppendLine("#nullable enable");
            code.AppendLine();

            // Usings
            code.AddUsing("System");
            code.AddUsing("System.Collections.Generic");
            code.AddUsing("Krampus.BinJson");
            code.AddUsing("Krampus.BinJson.Serialization");
            code.WriteUsings();

            // Namespace (if not global)
            if (!string.IsNullOrEmpty(model.Namespace))
            {
                using (code.Namespace(model.Namespace))
                {
                    EmitSerializerClass(code, model);
                }
            }
            else
            {
                EmitSerializerClass(code, model);
            }

            return code.ToString();
        }

        private static void EmitSerializerClass(CodeBuilder code, GeneratedTypeModel model)
        {
            // Class XML documentation
            code.XmlComment("summary", $"Auto-generated BJson serializer for {model.FullTypeName}");
            code.XmlComment("remarks", "This class was generated by BJsonSourceGenerator and provides optimized serialization without reflection.");

            // Class declaration
            using (code.Class("internal sealed", $"{model.TypeName}_BJsonSerializer", $"BJsonConverter<{model.TypeName}>"))
            {
                // Cached version fields
                EmitCachedVersionFields(code, model);

                // Serialize method
                EmitSerializeMethod(code, model);
                code.AppendLine();

                // Deserialize method
                EmitDeserializeMethod(code, model);
            }
        }

        private static void EmitSerializeMethod(CodeBuilder code, GeneratedTypeModel model)
        {
            code.XmlComment("summary", $"Serialize {model.TypeName} to BJsonValue");
            code.AppendLine($"public override BJsonValue Serialize({model.TypeName}? value, BJsonSerializationContext context)");

            using (code.Scope())
            {
                // Null check
                code.AppendLine("if (value == null)");
                using (code.Scope())
                {
                    code.AppendLine("return BJsonValue.Null;");
                }
                code.AppendLine();

                // Create BJsonObject
                code.AppendLine("var obj = new BJsonObject();");
                code.AppendLine();

                // Version local for predicates / mappers
                if (NeedsVersionLocal(model))
                    EmitVersionLocal(code, model);

                // Get serializable members sorted by Order
                var members = MemberOrdering.GetSerializableMembers(model.AllMembers);

                // Serialize each member
                foreach (var member in members)
                {
                    // Skip extension data member (handled separately)
                    if (member.IsExtensionData)
                        continue;

                    EmitMemberSerialization(code, member, model);
                }

                // Handle extension data
                if (model.ExtensionDataMember != null)
                {
                    code.AppendLine();
                    code.Comment("Extension data");
                    code.AppendLine($"if (value.{model.ExtensionDataMember.MemberName} != null)");
                    using (code.Scope())
                    {
                        code.AppendLine($"foreach (var kvp in value.{model.ExtensionDataMember.MemberName})");
                        using (code.Scope())
                        {
                            code.AppendLine("obj[kvp.Key] = kvp.Value;");
                        }
                    }
                }

                code.AppendLine();
                code.AppendLine("return BJsonValue.Create(obj);");
            }
        }

        private static void EmitMemberSerialization(CodeBuilder code, MemberModel member, GeneratedTypeModel model)
        {
            var jsonName = member.JsonName ?? member.MemberName;
            var memberAccess = $"value.{member.MemberName}";

            // Version range guard
            if (member.Version != null)
            {
                EmitVersionGuardOpen(code, member);
            }

            // Handle ignore conditions
            if (member.IgnoreCondition == IgnoreCondition.WhenWritingNull)
            {
                code.AppendLine($"if ({memberAccess} != null)");
                using (code.Scope())
                {
                    EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
                }
            }
            else if (member.IgnoreCondition == IgnoreCondition.WhenWritingDefault
                     || member.IgnoreCondition == IgnoreCondition.WhenWritingCustomDefault)
            {
                var typeString = code.FormatTypeName(member.MemberType);
                code.AppendLine($"if (!EqualityComparer<{typeString}>.Default.Equals({memberAccess}, default({typeString})))");
                using (code.Scope())
                {
                    EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
                }
            }
            else if (member.IgnoreCondition == IgnoreCondition.WhenWriting)
            {
                // WhenWriting: skip serialization entirely
            }
            else
            {
                // Never, Always (filtered upstream), WhenReading — always serialize
                EmitSerializeWithPredicate(code, jsonName, memberAccess, member, model);
            }

            if (member.Version != null)
            {
                EmitVersionGuardClose(code);
            }
        }

        private static void EmitSerializeWithPredicate(CodeBuilder code, string jsonName, string memberAccess, MemberModel member, GeneratedTypeModel model)
        {
            // Static predicate check
            if (member.IgnoreWhenMethod != null)
            {
                code.AppendLine($"if (!{model.TypeName}.{member.IgnoreWhenMethod}({memberAccess}, \"{jsonName}\", _version))");
                using (code.Scope())
                {
                    EmitPropertyAssignmentWithMapper(code, jsonName, memberAccess, member, model);
                }
            }
            else
            {
                EmitPropertyAssignmentWithMapper(code, jsonName, memberAccess, member, model);
            }
        }

        private static void EmitPropertyAssignmentWithMapper(CodeBuilder code, string jsonName, string memberAccess, MemberModel member, GeneratedTypeModel model)
        {
            string valueExpr;

            if (member.CustomConverterType != null)
            {
                valueExpr = $"new {member.CustomConverterType}().Serialize({memberAccess}, context)";
            }
            else
            {
                valueExpr = GetSerializationExpression(member.MemberType, memberAccess, "context");
            }

            // Value mapper (write direction)
            if (member.ValueMapperMethod != null)
                valueExpr = $"{model.TypeName}.{member.ValueMapperMethod}({valueExpr}, \"{jsonName}\", _version, false)";

            code.AppendLine($"obj[\"{jsonName}\"] = {valueExpr};");
        }

        /// <summary>
        /// Generate optimized serialization expression based on source type
        /// </summary>
        private static string GetSerializationExpression(string typeName, string valueExpression, string contextName)
        {
            // Strip nullable suffix for analysis
            var baseType = typeName.TrimEnd('?');

            // Primitives and simple types - use BJsonValue.Create directly
            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                case "byte":
                case "Byte":
                case "System.Byte":
                case "sbyte":
                case "SByte":
                case "System.SByte":
                case "short":
                case "Int16":
                case "System.Int16":
                case "ushort":
                case "UInt16":
                case "System.UInt16":
                case "int":
                case "Int32":
                case "System.Int32":
                case "uint":
                case "UInt32":
                case "System.UInt32":
                case "long":
                case "Int64":
                case "System.Int64":
                case "ulong":
                case "UInt64":
                case "System.UInt64":
                case "float":
                case "Single":
                case "System.Single":
                case "double":
                case "Double":
                case "System.Double":
                case "string":
                case "String":
                case "System.String":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonValue itself
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                    return valueExpression;

                // BJsonObject
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonArray
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                    return $"BJsonValue.Create({valueExpression})";

                // BJsonBinary
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return $"BJsonValue.Create({valueExpression})";

                // For all other types (complex objects, collections, enums, etc.)
                // use context.Serialize
                default:
                    return $"{contextName}.Serialize({valueExpression})";
            }
        }

        private static void EmitDeserializeMethod(CodeBuilder code, GeneratedTypeModel model)
        {
            code.XmlComment("summary", $"Deserialize BJsonValue to {model.TypeName}");
            code.AppendLine($"public override {model.TypeName}? Deserialize(BJsonValue value, BJsonSerializationContext context)");

            using (code.Scope())
            {
                // Null check
                code.AppendLine("if (value.IsNull)");
                using (code.Scope())
                {
                    code.AppendLine("return null;");
                }
                code.AppendLine();

                // Extract object
                code.AppendLine("var obj = value.ObjectValue;");
                code.AppendLine();

                // Version local for predicates / mappers
                if (NeedsVersionLocal(model))
                    EmitVersionLocal(code, model);
                code.AppendLine();

                // Get deserializable members
                var members = MemberOrdering.GetDeserializableMembers(model.AllMembers)
                    .Where(m => !m.IsExtensionData)
                    .ToList();

                // Track which properties were actually present in JSON (for required validation)
                var requiredMembers = members.Where(m => m.IsRequired).ToList();
                if (requiredMembers.Any())
                {
                    code.Comment("Track presence of required members");
                    foreach (var reqMember in requiredMembers)
                    {
                        code.AppendLine($"var _has_{reqMember.MemberName} = false;");
                    }
                    code.AppendLine();
                }

                // Handle constructor-based or factory-method-based deserialization
                var hasParameterizedFactory = !string.IsNullOrEmpty(model.Configuration.FactoryMethodName)
                    && model.Configuration.FactoryMethodParameters != null
                    && model.Configuration.FactoryMethodParameters.Count > 0;

                if ((model.Constructor != null && !model.Constructor.IsParameterless) || hasParameterizedFactory)
                {
                    EmitConstructorOrFactoryDeserialization(code, model, members, requiredMembers);
                }
                else
                {
                    // Parameterless constructor, parameterless factory, or value type
                    EmitParameterlessDeserialization(code, model, members, requiredMembers);
                }

                // Handle extension data
                if (model.ExtensionDataMember != null)
                {
                    code.AppendLine();
                    EmitExtensionDataDeserialization(code, model, members);
                }

                // Validate required members
                if (requiredMembers.Any())
                {
                    code.AppendLine();
                    EmitRequiredMemberValidation(code, requiredMembers);
                }

                code.AppendLine();
                code.AppendLine("return instance;");
            }
        }

        private static void EmitConstructorOrFactoryDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members, List<MemberModel> requiredMembers)
        {
            // Prefer factory method parameters over constructor if both exist
            var parameters = model.Configuration.FactoryMethodParameters ?? model.Constructor?.Parameters;
            var isUsingFactory = !string.IsNullOrEmpty(model.Configuration.FactoryMethodName) 
                && model.Configuration.FactoryMethodParameters != null;

            if (parameters == null || parameters.Count == 0)
            {
                // Fallback to parameterless if something went wrong
                EmitParameterlessDeserialization(code, model, members, requiredMembers);
                return;
            }

            code.Comment(isUsingFactory ? "Extract factory method parameters" : "Extract constructor parameters");

            // Extract each parameter from JSON
            foreach (var param in parameters)
            {
                // Use the pre-matched JsonName from parameter matching
                var jsonName = param.JsonName ?? param.ParameterName;

                // Check if this parameter corresponds to a required member
                var isRequired = param.MatchingMember?.IsRequired ?? false;

                EmitParameterExtraction(code, param, jsonName, isRequired);
            }

            code.AppendLine();
            code.Comment(isUsingFactory ? "Create instance via factory method" : "Create instance via constructor");

            var paramList = string.Join(", ", parameters.Select(p => p.ParameterName));
            if (!string.IsNullOrEmpty(model.Configuration.FactoryMethodName))
                code.AppendLine($"var instance = {model.TypeName}.{model.Configuration.FactoryMethodName}({paramList});");
            else
                code.AppendLine($"var instance = new {model.TypeName}({paramList});");
            code.AppendLine();

            // Set remaining properties not in constructor/factory parameters
            var paramNames = new HashSet<string>(
                parameters.Select(p => p.ParameterName),
                StringComparer.OrdinalIgnoreCase);

            var remainingMembers = members
                .Where(m => !paramNames.Contains(m.MemberName))
                .ToList();

            if (remainingMembers.Any())
            {
                code.Comment("Set remaining properties");
                foreach (var member in remainingMembers)
                {
                    EmitPropertyDeserialization(code, member, requiredMembers.Contains(member), model);
                }
            }
        }

        private static void EmitParameterlessDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members, List<MemberModel> requiredMembers)
        {
            code.Comment("Create instance");
            if (!string.IsNullOrEmpty(model.Configuration.FactoryMethodName))
                code.AppendLine($"var instance = {model.TypeName}.{model.Configuration.FactoryMethodName}();");
            else
                code.AppendLine($"var instance = new {model.TypeName}();");
            code.AppendLine();

            if (members.Any())
            {
                code.Comment("Deserialize properties");
                foreach (var member in members)
                {
                    EmitPropertyDeserialization(code, member, requiredMembers.Contains(member), model);
                }
            }
        }

        private static void EmitParameterExtraction(CodeBuilder code, ConstructorParameterModel param, string jsonName, bool isRequired)
        {
            code.AppendLine($"var {param.ParameterName} = obj.TryGetValue(\"{jsonName}\", out var {param.ParameterName}Value)");

            var deserializationCode = GetDeserializationExpression(param.ParameterType, $"{param.ParameterName}Value", "context");
            code.AppendLine($"    ? {deserializationCode}");
            code.AppendLine($"    : default({param.ParameterType});");

            // Track required member presence
            if (isRequired)
            {
                code.AppendLine($"if (obj.ContainsKey(\"{jsonName}\")) _has_{param.ParameterName} = true;");
            }
        }

        private static void EmitPropertyDeserialization(CodeBuilder code, MemberModel member, bool isRequired, GeneratedTypeModel model)
        {
            var jsonName = member.JsonName ?? member.MemberName;
            var legacyName = member.Version?.RenamedFrom;
            var varName = $"{member.MemberName}Value";
            var typeName = member.MemberType;

            // Version range guard
            if (member.Version != null)
                EmitVersionGuardOpen(code, member);

            // Build TryGetValue condition (with optional legacy name fallback)
            string tryGetCondition;
            if (legacyName != null)
                tryGetCondition = $"obj.TryGetValue(\"{jsonName}\", out var {varName}) || obj.TryGetValue(\"{legacyName}\", out {varName})";
            else
                tryGetCondition = $"obj.TryGetValue(\"{jsonName}\", out var {varName})";

            code.AppendLine($"if ({tryGetCondition})");
            using (code.Scope())
            {
                // Predicate check
                if (member.IgnoreWhenMethod != null)
                {
                    code.AppendLine($"if (!{model.TypeName}.{member.IgnoreWhenMethod}({varName}, \"{jsonName}\", _version))");
                    using (code.Scope())
                    {
                        EmitDeserializeAssignment(code, member, varName, isRequired, model);
                    }
                }
                else
                {
                    EmitDeserializeAssignment(code, member, varName, isRequired, model);
                }
            }

            // else: key absent — inject default value
            if (member.DefaultValue != null)
            {
                code.AppendLine("else");
                using (code.Scope())
                {
                    if (member.DefaultValue.HasProviderMethod)
                    {
                        code.AppendLine($"instance.{member.MemberName} = ({typeName})(object){model.TypeName}.{member.DefaultValue.ProviderMethod}()!;");
                    }
                    else if (member.DefaultValue.HasConstant)
                    {
                        var constVal = FormatConstantLiteral(member.DefaultValue.ConstantValue);
                        code.AppendLine($"instance.{member.MemberName} = ({typeName})(object){constVal}!;");
                    }

                    if (isRequired)
                        code.AppendLine($"_has_{member.MemberName} = true;");
                }
            }
            else if (isRequired)
            {
                code.AppendLine("else");
                using (code.Scope())
                {
                    code.AppendLine($"throw new System.InvalidOperationException($\"Required member '{jsonName}' was not present in the JSON.\");");
                }
            }

            if (member.Version != null)
                EmitVersionGuardClose(code);
        }

        private static void EmitDeserializeAssignment(CodeBuilder code, MemberModel member, string varName, bool isRequired, GeneratedTypeModel model)
        {
            // Value mapper (read direction) before deserialization
            string inputVar = varName;
            if (member.ValueMapperMethod != null)
            {
                code.AppendLine($"var {varName}_mapped = {model.TypeName}.{member.ValueMapperMethod}({varName}, \"{member.JsonName ?? member.MemberName}\", _version, true);");
                inputVar = $"{varName}_mapped";
            }

            if (member.CustomConverterType != null)
            {
                code.AppendLine($"instance.{member.MemberName} = new {member.CustomConverterType}().Deserialize({inputVar}, context);");
            }
            else
            {
                var deserializationCode = GetDeserializationExpression(member.MemberType, inputVar, "context");
                var requiresNullGuard = !member.IsNullable && !member.IsValueType && UsesContextDeserialize(member.MemberType);

                if (requiresNullGuard)
                {
                    code.AppendLine($"var deserialized{member.MemberName} = {deserializationCode};");
                    code.AppendLine($"if (deserialized{member.MemberName} != null)");
                    using (code.Scope())
                    {
                        code.AppendLine($"instance.{member.MemberName} = deserialized{member.MemberName};");
                    }
                }
                else
                {
                    code.AppendLine($"instance.{member.MemberName} = {deserializationCode};");
                }
            }

            if (isRequired)
                code.AppendLine($"_has_{member.MemberName} = true;");
        }

        /// <summary>
        /// Generate optimized deserialization expression based on target type
        /// </summary>
        private static string GetDeserializationExpression(string typeName, string valueName, string contextName)
        {
            // Strip nullable suffix for analysis
            var baseType = typeName.TrimEnd('?');

            // Primitives - use direct BJsonValue properties
            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                    return $"{valueName}.BoolValue";

                case "byte":
                case "Byte":
                case "System.Byte":
                    return $"{valueName}.ByteValue";

                case "sbyte":
                case "SByte":
                case "System.SByte":
                    return $"{valueName}.SByteValue";

                case "short":
                case "Int16":
                case "System.Int16":
                    return $"{valueName}.ShortValue";

                case "ushort":
                case "UInt16":
                case "System.UInt16":
                    return $"{valueName}.UShortValue";

                case "int":
                case "Int32":
                case "System.Int32":
                    return $"{valueName}.IntValue";

                case "uint":
                case "UInt32":
                case "System.UInt32":
                    return $"{valueName}.UIntValue";

                case "long":
                case "Int64":
                case "System.Int64":
                    return $"{valueName}.LongValue";

                case "ulong":
                case "UInt64":
                case "System.UInt64":
                    return $"{valueName}.ULongValue";

                case "float":
                case "Single":
                case "System.Single":
                    return $"{valueName}.FloatValue";

                case "double":
                case "Double":
                case "System.Double":
                    return $"{valueName}.DoubleValue";

                case "string":
                case "String":
                case "System.String":
                    return $"{valueName}.StringValue";

                // BJsonValue itself
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                    return valueName;

                // BJsonObject
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                    return $"{valueName}.ObjectValue";

                // BJsonArray
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                    return $"{valueName}.ArrayValue";

                // BJsonBinary
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return $"{valueName}.BinaryValue";

                // For all other types (complex objects, collections, enums, etc.)
                // use context.Deserialize<T>
                default:
                    return $"{contextName}.Deserialize<{typeName}>({valueName})";
            }
        }

        private static bool UsesContextDeserialize(string typeName)
        {
            var baseType = typeName.TrimEnd('?');

            switch (baseType)
            {
                case "bool":
                case "Boolean":
                case "System.Boolean":
                case "byte":
                case "Byte":
                case "System.Byte":
                case "sbyte":
                case "SByte":
                case "System.SByte":
                case "short":
                case "Int16":
                case "System.Int16":
                case "ushort":
                case "UInt16":
                case "System.UInt16":
                case "int":
                case "Int32":
                case "System.Int32":
                case "uint":
                case "UInt32":
                case "System.UInt32":
                case "long":
                case "Int64":
                case "System.Int64":
                case "ulong":
                case "UInt64":
                case "System.UInt64":
                case "float":
                case "Single":
                case "System.Single":
                case "double":
                case "Double":
                case "System.Double":
                case "string":
                case "String":
                case "System.String":
                case "BJsonValue":
                case "Krampus.BinJson.BJsonValue":
                case "BJsonObject":
                case "Krampus.BinJson.BJsonObject":
                case "BJsonArray":
                case "Krampus.BinJson.BJsonArray":
                case "BJsonBinary":
                case "Krampus.BinJson.BJsonBinary":
                    return false;

                default:
                    return true;
            }
        }

        private static void EmitExtensionDataDeserialization(CodeBuilder code, GeneratedTypeModel model, List<MemberModel> members)
        {
            var extensionMember = model.ExtensionDataMember!;
            var knownProperties = members.Select(m => m.JsonName ?? m.MemberName).ToList();

            code.Comment("Collect extension data (unknown properties)");
            code.AppendLine($"instance.{extensionMember.MemberName} = new Dictionary<string, BJsonValue>();");
            code.AppendLine("foreach (var kvp in obj)");
            using (code.Scope())
            {
                // Check if property is not in known list
                if (knownProperties.Any())
                {
                    var knownPropsArray = string.Join(", ", knownProperties.Select(p => $"\"{p}\""));
                    code.AppendLine($"if (!new[] {{ {knownPropsArray} }}.Contains(kvp.Key))");
                    using (code.Scope())
                    {
                        code.AppendLine($"instance.{extensionMember.MemberName}[kvp.Key] = kvp.Value;");
                    }
                }
                else
                {
                    code.AppendLine($"instance.{extensionMember.MemberName}[kvp.Key] = kvp.Value;");
                }
            }
        }

        /// <summary>
        /// Emit validation checks for required members
        /// </summary>
        private static void EmitRequiredMemberValidation(CodeBuilder code, List<MemberModel> requiredMembers)
        {
            code.Comment("Validate required members");

            foreach (var member in requiredMembers)
            {
                var jsonName = member.JsonName ?? member.MemberName;
                code.AppendLine($"if (!_has_{member.MemberName})");
                using (code.Scope())
                {
                    code.AppendLine($"throw new System.InvalidOperationException($\"Required member '{jsonName}' was not present in the JSON.\");");
                }
            }
        }

        private static bool NeedsVersionLocal(GeneratedTypeModel model)
        {
            if (model.Configuration.VersionContext != null)
                return true;

            foreach (var member in model.AllMembers)
            {
                if (member.Version != null || member.IgnoreWhenMethod != null || member.ValueMapperMethod != null)
                    return true;
            }

            return false;
        }

        private static void EmitVersionLocal(CodeBuilder code, GeneratedTypeModel model)
        {
            var vc = model.Configuration.VersionContext;
            if (vc == null)
            {
                code.AppendLine("System.IComparable? _version = null;");
            }
            else
            {
                code.AppendLine($"System.IComparable? _version = context.Options?.Version ?? _cachedContextVersion;");
            }
        }

        /// <summary>
        /// Emit cached static readonly fields for all versions used in the type
        /// </summary>
        private static void EmitCachedVersionFields(CodeBuilder code, GeneratedTypeModel model)
        {
            var vc = model.Configuration.VersionContext;
            if (vc == null)
                return; // No version context, nothing to cache

            // Collect all unique versions mentioned in the type
            var versions = new HashSet<string>(StringComparer.Ordinal);

            // Add the context version
            if (!string.IsNullOrEmpty(vc.IntroducedIn))
                versions.Add(vc.IntroducedIn!);

            // Add all member version boundaries
            foreach (var member in model.AllMembers)
            {
                if (member.Version != null)
                {
                    if (!string.IsNullOrEmpty(member.Version.IntroducedIn))
                        versions.Add(member.Version.IntroducedIn!);
                    if (!string.IsNullOrEmpty(member.Version.RemovedIn))
                        versions.Add(member.Version.RemovedIn!);
                }
            }

            if (versions.Count == 0)
                return;

            code.Comment("Cached parsed versions for performance");

            // Initialize the map
            _versionFieldMap = new Dictionary<string, string>();

            // Emit the main context version (always present if we have a version context)
            if (!string.IsNullOrEmpty(vc.IntroducedIn))
            {
                code.AppendLine($"private static readonly System.IComparable _cachedContextVersion = {vc.VersionTypeName}.Parse(\"{vc.IntroducedIn}\");");
                _versionFieldMap[vc.IntroducedIn!] = "_cachedContextVersion";
            }

            // Emit individual version fields for member boundaries
            var versionIndex = 0;

            foreach (var versionString in versions.OrderBy(v => v))
            {
                if (_versionFieldMap.ContainsKey(versionString))
                {
                    // Already emitted
                    continue;
                }

                var fieldName = $"_cachedVersion{versionIndex++}";
                _versionFieldMap[versionString] = fieldName;
                code.AppendLine($"private static readonly System.IComparable {fieldName} = {vc.VersionTypeName}.Parse(\"{versionString}\");");
            }

            code.AppendLine();
        }

        private static void EmitVersionGuardOpen(CodeBuilder code, MemberModel member)
        {
            var v = member.Version!;

            string GetVersionReference(string versionString)
            {
                // If we have a cached field, use it; otherwise, parse inline (fallback)
                if (_versionFieldMap != null && _versionFieldMap.TryGetValue(versionString, out var fieldName))
                {
                    return fieldName;
                }
                return $"{v.VersionTypeName}.Parse(\"{versionString}\")";
            }

            if (v.IntroducedIn != null && v.RemovedIn != null)
            {
                var introRef = GetVersionReference(v.IntroducedIn);
                var removedRef = GetVersionReference(v.RemovedIn);
                code.AppendLine($"if (_version == null || (_version.CompareTo({introRef}) >= 0 && _version.CompareTo({removedRef}) < 0))");
            }
            else if (v.IntroducedIn != null)
            {
                var introRef = GetVersionReference(v.IntroducedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({introRef}) >= 0)");
            }
            else if (v.RemovedIn != null)
            {
                var removedRef = GetVersionReference(v.RemovedIn);
                code.AppendLine($"if (_version == null || _version.CompareTo({removedRef}) < 0)");
            }
            code.OpenBrace();
        }

        private static void EmitVersionGuardClose(CodeBuilder code)
        {
            code.CloseBrace();
        }

        private static string FormatConstantLiteral(object? value)
        {
            if (value == null) return "null";
            if (value is string s) return $"\"{ s }\"";
            if (value is bool b) return b ? "true" : "false";
            if (value is char c) return $"'{c}'";
            if (value is float f) return $"{f}f";
            if (value is double d) return $"{d}";
            return value.ToString() ?? "default";
        }
    }
}
